// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeXmQoeC_3VMCsY90hAEDh7_STO1dpCW4',
    appId: '1:358519725314:web:e5675404647642936ef61b',
    messagingSenderId: '358519725314',
    projectId: 'rua11store-notifications-24f29',
    authDomain: 'rua11store-notifications-24f29.firebaseapp.com',
    storageBucket: 'rua11store-notifications-24f29.firebasestorage.app',
    measurementId: 'G-TQCM38XQCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSjQMAJpP1B-8KwJrpWVjySijWbq05EjY',
    appId: '1:358519725314:android:fec03ecdf81951b06ef61b',
    messagingSenderId: '358519725314',
    projectId: 'rua11store-notifications-24f29',
    storageBucket: 'rua11store-notifications-24f29.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-cd7QemE2T5y4TdJ7RcI0sKAbb5eVB5c',
    appId: '1:358519725314:ios:1994b7566cd444816ef61b',
    messagingSenderId: '358519725314',
    projectId: 'rua11store-notifications-24f29',
    storageBucket: 'rua11store-notifications-24f29.firebasestorage.app',
    iosBundleId: 'com.example.rua11storeCatalogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-cd7QemE2T5y4TdJ7RcI0sKAbb5eVB5c',
    appId: '1:358519725314:ios:1994b7566cd444816ef61b',
    messagingSenderId: '358519725314',
    projectId: 'rua11store-notifications-24f29',
    storageBucket: 'rua11store-notifications-24f29.firebasestorage.app',
    iosBundleId: 'com.example.rua11storeCatalogApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeXmQoeC_3VMCsY90hAEDh7_STO1dpCW4',
    appId: '1:358519725314:web:738965c6746bae886ef61b',
    messagingSenderId: '358519725314',
    projectId: 'rua11store-notifications-24f29',
    authDomain: 'rua11store-notifications-24f29.firebaseapp.com',
    storageBucket: 'rua11store-notifications-24f29.firebasestorage.app',
    measurementId: 'G-295M48WJ8D',
  );
}